name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    x86_test:
        name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:

                    - os: ubuntu-18.04
                      python-version: 3.7

        steps:
        - uses: actions/checkout@v2

        - name: Install OS dependencies
          shell: bash -l {0}
          run: |
              case "${{ runner.os }}" in
              Linux)
                sudo apt-get update -yy
                sudo apt-get install -yy  libsamplerate0 libsndfile1
                ;; 
              macOS)
                brew install libsamplerate
                ;;
              esac

        #- name: Cache conda
        # uses: actions/cache@v2
        # env:
        #   # Increase this value to reset cache if etc/example-environment.yml has not changed
        #   CACHE_NUMBER: 0
        # with:
        #   path: ~/conda_pkgs_dir
        #   key:
        #     ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
        #     hashFiles('etc/example-environment.yml') }}

        - name: Install Conda environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
            add-pip-as-python-dependency: true
            auto-activate-base: false
            activate-environment: test
            channel-priority: strict
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

        - name: Install conda dependencies
          shell: bash -l {0}
          run: |
            conda install -c conda-forge pip numpy scipy coverage scikit-learn!=0.19.0 matplotlib numba ffmpeg libsndfile pysoundfile coveralls

        - name: Conda info
          shell: bash -l {0}
          run: |
            conda info -a
            conda list

        - name: Install librosa
          shell: bash -l {0}
          run: python -m pip install --upgrade-strategy only-if-needed -e .[tests]

        - name: Run pytest
          shell: bash -l {0}
          run: pytest

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml
            directory: ./coverage/reports/
            flags: unittests
            env_vars: OS,PYTHON
            name: codecov-umbrella
            fail_ci_if_error: true
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: true
    
    armv64_job:
      name: Build and Test for arm64
      strategy:
        matrix:
          pyver: [cp37-cp37m]
      runs-on: ubuntu-18.04
      env:
        py: /opt/python/${{ matrix.pyver }}/bin/python
        img: quay.io/pypa/manylinux2014_aarch64  
    
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
      
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              ${{ env.img }} \
              bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
              source .env/bin/activate && \
              yum install -y update && \
              yum install -y wget && \

              python -m pip install --upgrade pip && \
              python --version && \
            
              uname -m && \
              yum install -y libsamplerate0 libsndfile1
              whoami && \
              wget -q "https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh" -O miniconda.sh && \
              chmod +x miniconda.sh && \
              ./miniconda.sh -u -b -p $HOME/miniconda3 && \
              export PATH=$HOME/miniconda3/bin:$PATH && \

              ~/miniconda3/bin/conda install conda-build -y && \
              ~/miniconda3/bin/conda create -q -y --name testenv python=3.7 cython numpy pytest psutil pip && \
              source ~/miniconda3/bin/activate testenv && \
              conda --version && \
              conda install -c conda-forge pip numpy scipy coverage scikit-learn!=0.19.0 matplotlib numba ffmpeg libsndfile pysoundfile coveralls && \
              conda info -a
              conda list
              python --version && \
              pwd && \
              ls && \
              python --version && \
              python -m pip install --upgrade-strategy only-if-needed -e .[tests]
              pytest
              deactivate'
